docs: Remove constructor
Tuna-Shih/todo pull request #17
Opened 2020-05-11 14:54 UTC by Tuna-Shih

2020-05-11 15:03 UTC, HsuTing requested changes

2020-05-11 15:03 UTC, HsuTing commented on src/TodoItem.js
> +        <button className="add-todo" onClick={this.add.bind(this)}>
這樣會每次重新 render 會重複 bind
沒有意義

2020-05-11 15:06 UTC, HsuTing commented
再來寫出兩種寫法的優劣

2020-05-12 06:40 UTC, Tuna-Shih commented on src/TodoItem.js
> +        <button className="add-todo" onClick={this.add.bind(this)}>
改為arrow function 移除bind(this)

2020-05-12 07:41 UTC, Tuna-Shih commented
> 再來寫出兩種寫法的優劣



> 再來寫出兩種寫法的優劣

這兩種寫法差不多，class property的寫法是一種語法糖

2020-05-12 07:54 UTC, HsuTing approved these changes

2020-05-12 07:56 UTC, HsuTing commented
> > 再來寫出兩種寫法的優劣
> 
> 這兩種寫法差不多，class property的寫法是一種語法糖

不對，兩個寫法都是 class 你解釋 class property？
再多回答一個問題，什麼叫做語法糖？

2020-05-12 15:09 UTC, Tuna-Shih commented
constructor 寫法  效能較佳，但code較長且要bind
去除 constructor ，使用arrow function 可以不用在constructor重複bind，code較短且易讀

2020-05-12 15:24 UTC, merged