feat: uuid
Tuna-Shih/todo pull request #19
Opened 2020-05-12 08:24 UTC by Tuna-Shih

use uuid instead of id++

2020-05-12 13:25 UTC, HsuTing requested changes

2020-05-12 13:25 UTC, HsuTing commented on package.json
> +    "react-uuid": "^1.0.2"
用另外一個套件

2020-05-12 13:27 UTC, HsuTing commented
問題1 uuid 的好處在哪

2020-05-12 13:28 UTC, HsuTing commented on src/App.js
> +            <Todo key={uuid()} todo={todo} deleteTodo={this.deleteTodo} />
問題二 這樣會造成一個問題 是甚麼問題

2020-05-12 14:35 UTC, Tuna-Shih commented on src/App.js
> +            <Todo key={uuid()} todo={todo} deleteTodo={this.deleteTodo} />
UUID 優點 為獨立不重複

造成問題為效率較差

2020-05-12 15:24 UTC, HsuTing commented on src/App.js
> +            <Todo key={uuid()} todo={todo} deleteTodo={this.deleteTodo} />
詳細解釋 效能問題是在哪邊

2020-05-12 15:25 UTC, HsuTing approved these changes

2020-05-12 15:36 UTC, Tuna-Shih commented on src/App.js
> +            <Todo key={uuid()} todo={todo} deleteTodo={this.deleteTodo} />
key用來區分各個child component，只需要相對unique，uuid雖然為獨立，但是字碼多，儲存空間大

2020-05-13 01:43 UTC, HsuTing commented on src/App.js
> +            <Todo key={uuid()} todo={todo} deleteTodo={this.deleteTodo} />
對一半

2020-05-13 07:34 UTC, Tuna-Shih commented on src/App.js
> +            <Todo key={uuid()} todo={todo} deleteTodo={this.deleteTodo} />
key是react用來分辨component，每當修改component時，react會用key去分辨哪些可保留，那些要重新render，用unstable的key會使react判斷不相同，導致多餘的render，產生效能問題

2020-05-13 07:37 UTC, HsuTing commented on src/App.js
> +            <Todo key={uuid()} todo={todo} deleteTodo={this.deleteTodo} />
給過

2020-05-13 07:37 UTC, HsuTing commented
@Tuna-Shih 解 conflict 才能 merge

2020-05-13 07:47 UTC, HsuTing requested changes

2020-05-13 07:47 UTC, HsuTing commented on src/App.js
> +  id = 1;
這個不用留著

2020-05-13 07:59 UTC, HsuTing approved these changes

2020-05-13 07:59 UTC, merged