feat: prop-type
Tuna-Shih/todo pull request #20
Opened 2020-05-14 08:26 UTC by Tuna-Shih

2020-05-14 08:31 UTC, HsuTing requested changes
該 required 的就該 required

2020-05-14 08:31 UTC, HsuTing commented on src/Todo.js
> +  todo: PropTypes.object,
不要用 object
額外工作：去裝 `eslint-config-google`, `eslint-config-fbjs`
extend 順序是
```
[
  'fbjs/strict',
  'google',
]
```

2020-05-14 08:32 UTC, HsuTing commented
問題 1. 為什麼要用 prop-types，用了的優缺點

2020-05-14 13:52 UTC, HsuTing commented on src/Todo.js
> +  todo: PropTypes.object,
改成

```
 extends: [
    'fbjs/strict',
    'google',
    'plugin:prettier/recommended',
    'prettier/standard',
  ],
```

2020-05-14 16:44 UTC, Tuna-Shih commented
> 問題 1. 為什麼要用 prop-types，用了的優缺點

因為JS是弱型別，宣告並不明確，傳props時為了判斷是否為需求型態，用prop-types去做判斷

2020-05-15 07:34 UTC, HsuTing requested changes

2020-05-15 07:34 UTC, HsuTing commented on src/TodoItem.js
> +import PropTypes from "prop-types";
這一看就是沒有跑過 prettier

2020-05-15 07:34 UTC, HsuTing commented on src/Todo.js
> +};
required ?

2020-05-15 10:10 UTC, Tuna-Shih commented on src/TodoItem.js
> +import PropTypes from "prop-types";
prettier要設定甚麼嗎

2020-05-15 10:11 UTC, HsuTing commented on src/TodoItem.js
> +import PropTypes from "prop-types";
不用啊 只要跑過就行了

2020-05-15 10:12 UTC, Tuna-Shih commented on src/TodoItem.js
> +import PropTypes from "prop-types";
我跑prettier就是這樣耶，哪邊有問題

2020-05-15 10:16 UTC, HsuTing commented on src/TodoItem.js
> +import PropTypes from "prop-types";
不可能 你自己設定 `singleQuote: true` 跑完不會是雙引號

2020-05-15 10:20 UTC, HsuTing commented
新增 task: css 也要 prettier 過

2020-05-15 15:06 UTC, closed without merging