feat: Edit todo
Tuna-Shih/todo pull request #21
Opened 2020-05-14 08:33 UTC by Tuna-Shih

2020-05-14 08:42 UTC, HsuTing requested changes

2020-05-14 08:42 UTC, HsuTing commented on src/Todo.js
> +          </button>
不要用 display 來決定要不要顯示，非必要不要這樣寫

2020-05-14 08:42 UTC, HsuTing commented on src/Todo.js
> +            placeholder={todo.text}
正常狀況應該會是 edit 時候 把 text 設定成 editText

2020-05-14 08:42 UTC, HsuTing commented on src/App.js
> +  handleSubmit = (id, editTodo) => {
建議重新命名 我會覺得  editTodo 會比較明確

2020-05-14 08:42 UTC, HsuTing commented on src/Todo.js
> +  edit = () => {
通常會用  toggle.... 之類的命名

2020-05-14 12:21 UTC, Tuna-Shih commented on src/Todo.js
> +            placeholder={todo.text}
你是指在edit時  輸入文字會同時修改list內的object嗎

2020-05-14 14:29 UTC, HsuTing commented on src/Todo.js
> +            placeholder={todo.text}
在你按下去 edit 的時候

2020-05-15 01:25 UTC, HsuTing approved these changes

2020-05-15 01:25 UTC, HsuTing commented on src/Todo.js
> +      <div className='list-item'>
你的 prettier 設定值是什麼？
正常這邊應該要是雙引號
而且 lint 應該也會要你是雙引號？

2020-05-15 04:33 UTC, Tuna-Shih commented on src/Todo.js
> +      <div className='list-item'>
改prettier的設定了

2020-05-15 04:40 UTC, HsuTing commented on src/Todo.js
> +      <div className='list-item'>
不是改 single quote 是改 https://prettier.io/docs/en/options.html#jsx-quotes

2020-05-16 07:50 UTC, HsuTing requested changes

2020-05-16 07:50 UTC, HsuTing commented on src/Todo.js
> +  }),
不用 required?

2020-05-16 08:03 UTC, HsuTing approved these changes

2020-05-16 08:03 UTC, merged