Infinite scroll
Tuna-Shih/todo pull request #23
Opened 2020-05-17 17:47 UTC by Tuna-Shih

2020-05-18 01:24 UTC, HsuTing requested changes

2020-05-18 01:24 UTC, HsuTing commented on src/App.css
> +
這一個空格是要？

2020-05-18 01:24 UTC, HsuTing commented on src/App.js
> +import TodoList from './TodoList';
為什麼要重新命名？

2020-05-18 01:24 UTC, HsuTing commented on src/App.js
> +          {loading ? <p className="App-intro">loading ...</p> : ''}
你有寫 App-intro ?

2020-05-18 01:24 UTC, HsuTing commented on src/App.css
> +  height: 230px;
誰跟你說要定高了？

2020-05-18 01:24 UTC, HsuTing commented on src/App.js
> +    oldTodos: [],
不要存兩次 todo，沒必要

2020-05-18 01:24 UTC, HsuTing commented on src/App.js
> +    }, 100);
我又沒叫你寫 loading 你這邊也不需要寫 loading 吧

2020-05-18 01:24 UTC, HsuTing commented on src/App.js
> +    items: 10,
這不是我要的
給你一個提示 你應該存的是最後一個 todo 的 uuid 以及是否有更多資料

ex:

```
{
  hasNextPage: true,
  endCursor: 'uuid',
}
```

2020-05-18 01:24 UTC, HsuTing commented on src/App.js
> +        oldTodos: [{ id: uuidv4(), text: todoText }, ...oldTodos]
你這樣寫法 新增的兩個 new todo id 會不一樣，不過反正都不是我要的

2020-05-18 02:18 UTC, Tuna-Shih commented on src/App.js
> +import TodoList from './TodoList';
list比較好區分

2020-05-18 02:22 UTC, HsuTing commented on src/App.js
> +import TodoList from './TodoList';
那你應該改的是 TodoItem
List 結尾通常應該是要 array compoment

2020-05-18 05:30 UTC, Tuna-Shih commented on src/App.js
> +          {loading ? <p className="App-intro">loading ...</p> : ''}
沒有

2020-05-18 05:30 UTC, Tuna-Shih commented on src/App.css
> +  height: 230px;
沒訂高沒有scroll

2020-05-18 05:31 UTC, HsuTing commented on src/App.js
> +          {loading ? <p className="App-intro">loading ...</p> : ''}
在複製貼上啊 被抓到了吼

2020-05-18 05:32 UTC, HsuTing commented on src/App.css
> +  height: 230px;
來 如果你有沒有定高 有出現捲軸 怎辦？

2020-05-18 10:02 UTC, Tuna-Shih commented on src/App.js
> +          {loading ? <p className="App-intro">loading ...</p> : ''}
學習從複製貼上開始

2020-05-18 13:25 UTC, HsuTing requested changes

2020-05-18 13:25 UTC, HsuTing commented on package.json
> +    "react-infinite-scroller": "^1.2.4",
阿是有用到喔？

2020-05-20 01:15 UTC, HsuTing requested changes

2020-05-20 01:15 UTC, HsuTing commented on public/index.html
> +    <link rel="stylesheet" href="" />
?

2020-05-20 01:15 UTC, HsuTing commented on src/App.js
> +import TodoList from './TodoList';
裝死？

2020-05-20 01:15 UTC, HsuTing commented on src/App.js
> +import axios from 'axios';
用原生 fetch

2020-05-20 01:15 UTC, HsuTing commented on src/App.js
> +    // }
不會用到的註解刪掉

2020-05-20 01:15 UTC, HsuTing commented on src/App.js
> +    count: 25
不是說不要用 count ?

2020-05-21 05:59 UTC, HsuTing requested changes

2020-05-21 05:59 UTC, HsuTing commented on package.json
> +    "json-server": "json-server --watch db.json --port 3003"
沒用到東西就拿掉

2020-05-21 05:59 UTC, HsuTing commented on src/App.js
> +    start: 30
30 ?

2020-05-21 05:59 UTC, HsuTing commented on src/App.js
> +  loadData = (first, after) => {
我明明說 after 的意思是 id 是要找在那個 id 之後幾個 first

2020-05-21 05:59 UTC, HsuTing commented on src/App.js
> +    const preTodos = todos;
寫法應該是這樣 `const { start, todos: preTodos } = this.state;`

2020-05-21 05:59 UTC, HsuTing commented on src/App.js
> +    const conCatData = preTodos.concat(moreData);
寫法應該是 `[...preTodos, ...moreData]`;

2020-05-21 05:59 UTC, HsuTing commented on src/App.js
> +        this.setState({ todos: loadRange });
你太多次 setState 是一件很沒有效率的事情

2020-05-21 06:03 UTC, Tuna-Shih commented on src/App.js
> +  loadData = (first, after) => {
first: 10  => 1 -9
first: 10, after: 4 => 11-14
這樣子?

2020-05-21 06:05 UTC, HsuTing commented on src/App.js
> +  loadData = (first, after) => {
不是 after 是 id
應該會是 `28e03a35-9ea9-49a5-b82c-34a95a55e974` 之類的
你要找他在 todo 位置哪裡 然後拿他後面 frist 個 todo

2020-05-21 13:30 UTC, HsuTing requested changes

2020-05-21 13:30 UTC, HsuTing commented on package.json
> +    "json-server": "json-server --watch db.json --port 3003"
????

2020-05-21 13:30 UTC, HsuTing commented on src/App.js
> +      }, 1000);
set timeout 沒意義

2020-05-21 15:47 UTC, HsuTing requested changes
沒用到的東西刪掉
有改好的要按 resolve conversation

2020-05-21 16:01 UTC, HsuTing approved these changes

2020-05-21 16:02 UTC, merged