feat: less
Tuna-Shih/todo pull request #26
Opened 2020-05-25 12:14 UTC by Tuna-Shih

2020-05-25 14:10 UTC, HsuTing requested changes

2020-05-25 14:10 UTC, HsuTing commented on package.json
> +  "jest": {
拆成單獨 config

2020-05-25 14:10 UTC, HsuTing commented on package.json
> +  "babel": {
拆成單獨 config

2020-05-25 14:10 UTC, HsuTing commented on package.json
> +  "jest": {
eslintConfig, browserslist 也是

2020-05-25 14:10 UTC, HsuTing commented
css module 呢？

2020-05-25 14:12 UTC, HsuTing commented
問題 1. 用 less 好處在哪
問題 2. 為什麼要用 css module
問題 3. react create app eject 做了什麼事情

2020-05-26 01:06 UTC, HsuTing commented
問題4. css in js 跟 css 差別在哪，有缺點在哪

2020-05-28 07:02 UTC, Tuna-Shih commented
1.less讓寫css時多了variables、functions、mixins......等功能，更加具有邏輯，減少開發時間及方便維護

2.css module可以使className獨特，避免重複

3.create-react-app內建許多配置，並隱藏起來，eject後會將隱藏的顯現出來(ex : webpack)

2020-05-28 08:27 UTC, Tuna-Shih commented
4.css in js就是將css寫在JavaScript裡面，因此可以使用JS的功能，像是variables、functions或是邏輯判斷等

缺點為：Runtime cost(由於會動態生成css)、Unreadable class names(自動生成的class name造成可讀性降低)、No interoperability(沒有統一的標準)

2020-05-28 08:29 UTC, HsuTing commented
> 4.css in js就是將css寫在JavaScript裡面，因此可以使用JS的功能，像是variables、functions或是邏輯判斷等
> 
> 缺點為：Runtime cost(由於會動態生成css)、Unreadable class names(自動生成的class name造成可讀性降低)、No interoperability(沒有統一的標準)

我打錯字 是優缺點，然後缺點不是這個 你這些說的應該是 styled component 吧？

2020-06-13 05:52 UTC, HsuTing commented on src/Todo.js
> +console.log(styles);
刪掉

2020-06-13 05:52 UTC, HsuTing approved these changes

2020-06-13 05:56 UTC, merged