feat: function component
Tuna-Shih/todo pull request #33
Opened 2020-06-23 03:50 UTC by Tuna-Shih

2020-06-23 05:39 UTC, HsuTing requested changes
- [ ] function 應該都要用 useCallback
- [ ] react hook deps 應該要有東西 (eslint 理論上應該要不過才對)
- [ ] react.memo 呢？
- [ ] 拆檔案呢？

2020-06-23 05:39 UTC, HsuTing commented on src/components/TodoItem.js
> +  const { todoText, deleteAllTodo, handleChange, addTodo } = props;
這樣寫這樣

```js
const TodoItem = ({ todoText, deleteAllTodo, handleChange, addTodo }) => {
  ...
};

export default React.memo(TodoItem);
```

2020-06-25 11:48 UTC, HsuTing requested changes
??????

2020-06-28 22:13 UTC, Tuna-Shih commented
> ??????
這樣改可以嗎

2020-06-29 01:05 UTC, HsuTing requested changes
1. 你要思考什麼應該要寫成獨立 function 什麼只需要寫成類似這樣

```
<div onClick={() => doThing('test')} />
```

2. 什麼變數應該跟其他 function 共用，什麼變數應該只要包在 function 裡面，什麼變數應該在 fucntion return 時候給出來

3. hook 跟 filename 的名稱要更有語意，然後只有一個時候應該寫成 export default

4. 你要花更多時間思考，看你 code 的人 怎樣解讀比較快，還有對於未來如果要維護的人，怎樣理解語意比較清楚

2020-06-29 01:06 UTC, HsuTing commented
> > ??????
> > 這樣改可以嗎

是一種想法，但是不行，太醜，而且有點多此一舉

2020-06-30 01:33 UTC, HsuTing requested changes
- 方向算對的 但是思考不足
- arrow function 是可以寫成

```
export default a => useCallback(() => {
});
```

- prettier 看起來就沒跑

2020-06-30 01:33 UTC, HsuTing commented on src/components/hooks/useOnFinish.js
> +  }, [inputData]);
inputData 應該是在 useCallback 裡面

2020-06-30 01:33 UTC, HsuTing commented on src/components/hooks/useHandleValidation.js
> +  }, [todoText, addTodo]);
你在思考一下 哪些該被放到這個 hook 裡面

2020-06-30 01:33 UTC, HsuTing commented on src/components/hooks/useSubmitEdit.js
> +  }, [input, stateFunction]);
這我會寫在 dom 上面 他不屬於邏輯多到需要單獨寫成 function or hook

2020-06-30 01:33 UTC, HsuTing commented on src/components/hooks/useCheckOverFlow.js
> +  }, [input, stateFunction]);
再想想哪些應該要放進來

2020-06-30 01:33 UTC, HsuTing commented on src/components/hooks/useApp.js
> +  );
??

2020-07-02 16:43 UTC, HsuTing requested changes

2020-07-02 16:43 UTC, HsuTing commented on src/components/Todo.js
> +  useEffect(checkOverflow);
useCheckOverflow 你再想想

2020-07-02 16:43 UTC, HsuTing commented on src/components/TodoItem.js
> +  });
useHandleValidation 你再想想

2020-07-02 16:43 UTC, HsuTing commented on src/components/App.js
> +  );
useAutoLoad 再想想

2020-07-02 16:43 UTC, HsuTing commented on src/components/App.js
> +  );
useHandleScroll 再想想

2020-07-02 16:43 UTC, HsuTing commented on src/components/hooks/loadMore.js
> +};
hooks 都必須是 hook
要不你就放到 utils

2020-07-04 14:36 UTC, HsuTing reviewed
(看下面那個 review )

2020-07-04 14:58 UTC, HsuTing requested changes
- return 不用所有都需要是 object
-  argument 可以合成一個 object 
- import 東西順序 先 packeges 在 relative path 比較清楚
- arrow function 單純 return 東西時候 寫成

```
const a = argu => useCallback(() => { ... }, []);
```
- arguments 該拆就拆 不然很難閱讀

2020-07-04 14:58 UTC, HsuTing commented on src/components/hooks/useHandleScroll.js
> +  const handleScroll = () => {
這應該定義在 useEffect 裡面

2020-07-04 14:58 UTC, HsuTing commented on src/components/hooks/useHandleValidation.js
> +  };
你的 useCallback 呢？

2020-07-04 14:58 UTC, HsuTing commented on src/components/hooks/useHandleValidation.js
> +  };
我傾 return setTodoText 就可以了

2020-07-04 14:58 UTC, HsuTing commented on src/components/hooks/useAutoLoad.js
> +  }, [stop]);
這樣寫法 有個問題，如果畫面很長 你會一直觸發 setState
導致 component 一直 render 
會讓效能不好

2020-07-06 14:10 UTC, HsuTing requested changes

2020-07-06 14:10 UTC, HsuTing commented on src/components/FormList.js
>  import isMobilePhone from 'validator/lib/isMobilePhone';
?

2020-07-06 14:10 UTC, HsuTing commented on src/components/hooks/useAutoLoad.js
> +      if (todos.length < todosLength && todos.length <= 15) {
???

2020-07-07 09:31 UTC, HsuTing requested changes

2020-07-07 09:31 UTC, HsuTing commented on src/components/utils/loadMore.js
> +  const loadData = (first, after) => {
這邊為什麼要寫成 function ?

2020-07-07 09:31 UTC, HsuTing commented on src/components/utils/loadMore.js
> +      todosLength: todoData.length
通常會用 total

2020-07-07 09:31 UTC, HsuTing commented on src/components/hooks/useAutoLoad.js
> +    function auto({ endCursor, todos }) {
function ?

2020-07-07 09:32 UTC, HsuTing commented
> * 方向算對的 但是思考不足
> * arrow function 是可以寫成
> 
> ```
> export default a => useCallback(() => {
> });
> ```
> 
> * prettier 看起來就沒跑

@Tuna-Shih 你確定你有做到？

2020-07-07 09:43 UTC, Tuna-Shih commented on src/components/utils/loadMore.js
> +  const loadData = (first, after) => {
沒有用到其他hook，也只有要return值

2020-07-07 14:22 UTC, HsuTing approved these changes

2020-07-07 14:22 UTC, HsuTing commented on src/components/utils/loadMore.js
> +  if (!getData) return [];
這個 return 有問題

2020-07-07 14:31 UTC, merged